version: '2'

networks:
  app-network:
    driver: bridge

services:
  redis:
    image: 'bitnami/redis:latest'
    networks:
      - app-network

  web:
    build: .
    ports:
     - "5000:5000"
    volumes:
     - .:/code
    networks:
      - app-network