version: '2'

networks:
  app-network:
    driver: bridge

services:
  redis:
    image: 'bitnami/redis:latest'
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
    networks:
      - app-network

  web:
    build: .
    ports:
     - "5000:5000"
    volumes:
     - .:/home/app
    networks:
      - app-network